language: python
python:
  - "2.7"
install:
  # Build/test dependencies
  - pip install -r tca/requirements.txt --use-mirrors
  # The coverage tool
  - pip install coverage --use-mirrors
script:
  - coverage run --source='tca/.' tca/manage.py test tca/ && coverage report --fail-under=95
